# Gradle
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.caching=true

# Minecraft / NeoForge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.176
neo_version_range=[21.1.0,)
loader_version_range=[4,)

# Mod properties
mod_id=xbob
mod_name=Crosshair Bobbing Remake
mod_version=1.9fix
mod_license=GPL-3.0
mod_authors=Krash220, xuanwz_11353
mod_description=Make the crosshair follows the view bobbing.
mod_url=https://github.com/xuanwz11353/CrosshairBobbingMod-Fabric-1.21.1
mod_package=krash220.xbob

# Maven
maven_group=krash220.xbob
archives_base_name=xbob
